version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/web
permissions:
  - object: /home/ubuntu/web
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
       - file
